<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **Space X  Falcon 9 First Stage Landing Prediction**

## Web scraping Falcon 9 and Falcon Heavy Launches Records from Wikipedia

Estimated time needed: **40** minutes

In this lab, you will be performing web scraping to collect Falcon 9 historical launch records from a Wikipedia page titled `List of Falcon 9 and Falcon Heavy launches`

https://en.wikipedia.org/wiki/List_of_Falcon_9_and_Falcon_Heavy_launches

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_1_L2/images/Falcon9_rocket_family.svg)

Falcon 9 first stage will land successfully

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0701EN-SkillsNetwork/api/Images/landing_1.gif)

Several examples of an unsuccessful landing are shown here:

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0701EN-SkillsNetwork/api/Images/crash.gif)

More specifically, the launch records are stored in a HTML table shown below:

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_1_L2/images/falcon9-launches-wiki.png)

  ## Objectives
Web scrap Falcon 9 launch records with `BeautifulSoup`: 
- Extract a Falcon 9 launch records HTML table from Wikipedia
- Parse the table and convert it into a Pandas data frame

First let's import required packages for this lab

In [1]:
!pip3 install beautifulsoup4
!pip3 install requests

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Requirement already satisfied: beautifulsoup4 in /opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages (4.11.1)
Requirement already satisfied: soupsieve>1.2 in /opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages (from beautifulsoup4) (2.3.1)
Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Requirement already satisfied: requests in /opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages (from requests) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages (from requests) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages (from requests) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages (from requests) (2021.10.8)

In [3]:
import sys

import requests
from bs4 import BeautifulSoup
import re
import unicodedata
import pandas as pd

and we will provide some helper functions for you to process web scraped HTML table

In [5]:
def date_time(table_cells):
    """
    This function returns the data and time from the HTML  table cell
    Input: the  element of a table data cell extracts extra row
    """
    return [data_time.strip() for data_time in list(table_cells.strings)][0:2]

def booster_version(table_cells):
    """
    This function returns the booster version from the HTML  table cell 
    Input: the  element of a table data cell extracts extra row
    """
    out=''.join([booster_version for i,booster_version in enumerate( table_cells.strings) if i%2==0][0:-1])
    return out

def landing_status(table_cells):
    """
    This function returns the landing status from the HTML table cell 
    Input: the  element of a table data cell extracts extra row
    """
    out=[i for i in table_cells.strings][0]
    return out


def get_mass(table_cells):
    mass=unicodedata.normalize("NFKD", table_cells.text).strip()
    if mass:
        mass.find("kg")
        new_mass=mass[0:mass.find("kg")+2]
    else:
        new_mass=0
    return new_mass


def extract_column_from_header(row):
    """
    This function returns the landing status from the HTML table cell 
    Input: the  element of a table data cell extracts extra row
    """
    if (row.br):
        row.br.extract()
    if row.a:
        row.a.extract()
    if row.sup:
        row.sup.extract()
        
    colunm_name = ' '.join(row.contents)
    
    # Filter the digit and empty names
    if not(colunm_name.strip().isdigit()):
        colunm_name = colunm_name.strip()
        return colunm_name

To keep the lab tasks consistent, you will be asked to scrape the data from a snapshot of the  `List of Falcon 9 and Falcon Heavy launches` Wikipage updated on
`9th June 2021`

In [7]:
static_url = "https://en.wikipedia.org/w/index.php?title=List_of_Falcon_9_and_Falcon_Heavy_launches&oldid=1027686922"

Next, request the HTML page from the above URL and get a `response` object

### TASK 1: Request the Falcon9 Launch Wiki page from its URL

First, let's perform an HTTP GET method to request the Falcon9 Launch HTML page, as an HTTP response.

In [9]:
response = requests.get(static_url)

Create a `BeautifulSoup` object from the HTML `response`

In [11]:
# Use BeautifulSoup() to create a BeautifulSoup object from a response text content
beautiful_soup_obj = BeautifulSoup(response.text)

Print the page title to verify if the `BeautifulSoup` object was created properly

In [13]:
# Use soup.title attribute
beautiful_soup_obj.title

### TASK 2: Extract all column/variable names from the HTML table header

Next, we want to collect all relevant column names from the HTML table header

Let's try to find all tables on the wiki page first. If you need to refresh your memory about `BeautifulSoup`, please check the external reference link towards the end of this lab

In [124]:
# Use the find_all function in the BeautifulSoup object, with element type `table`
# Assign the result to a list called `html_tables`
html_tables = beautiful_soup_obj.find_all("table")

Starting from the third table is our target table contains the actual launch records.

In [126]:
# Let's print the third table and check its content
first_launch_table = html_tables[2]
#print(first_launch_table)

You should able to see the columns names embedded in the table header elements `<th>` as follows:

```
<tr>
<th scope="col">Flight No.
</th>
<th scope="col">Date and<br/>time (<a href="/wiki/Coordinated_Universal_Time" title="Coordinated Universal Time">UTC</a>)
</th>
<th scope="col"><a href="/wiki/List_of_Falcon_9_first-stage_boosters" title="List of Falcon 9 first-stage boosters">Version,<br/>Booster</a> <sup class="reference" id="cite_ref-booster_11-0"><a href="#cite_note-booster-11">[b]</a></sup>
</th>
<th scope="col">Launch site
</th>
<th scope="col">Payload<sup class="reference" id="cite_ref-Dragon_12-0"><a href="#cite_note-Dragon-12">[c]</a></sup>
</th>
<th scope="col">Payload mass
</th>
<th scope="col">Orbit
</th>
<th scope="col">Customer
</th>
<th scope="col">Launch<br/>outcome
</th>
<th scope="col"><a href="/wiki/Falcon_9_first-stage_landing_tests" title="Falcon 9 first-stage landing tests">Booster<br/>landing</a>
</th></tr>
```

Next, we just need to iterate through the `<th>` elements and apply the provided `extract_column_from_header()` to extract column name one by one

In [128]:
column_names = []
for tr_el in first_launch_table.find_all("th"):
    header_name = extract_column_from_header(tr_el)
    if(header_name is not None and len(header_name) > 0):
         column_names.append(header_name)
print(column_names)

['Flight No.', 'Date and time ( )', 'Launch site', 'Payload', 'Payload mass', 'Orbit', 'Customer', 'Launch outcome']

Check the extracted column names

In [21]:
print(column_names)

['Flight No.', 'Date and time ( )', 'Launch site', 'Payload', 'Payload mass', 'Orbit', 'Customer', 'Launch outcome']

## TASK 3: Create a data frame by parsing the launch HTML tables

We will create an empty dictionary with keys from the extracted column names in the previous task. Later, this dictionary will be converted into a Pandas dataframe

In [148]:
launch_dict= dict.fromkeys(column_names)

# Remove an irrelvant column
del launch_dict['Date and time ( )']

# Let's initial the launch_dict with each value to be an empty list
launch_dict['Flight No.'] = []
launch_dict['Launch site'] = []
launch_dict['Payload'] = []
launch_dict['Payload mass'] = []
launch_dict['Orbit'] = []
launch_dict['Customer'] = []
launch_dict['Launch outcome'] = []
# Added some new columns
launch_dict['Version Booster']=[]
launch_dict['Booster landing']=[]
launch_dict['Date']=[]
launch_dict['Time']=[]

Next, we just need to fill up the `launch_dict` with launch records extracted from table rows.

Usually, HTML tables in Wiki pages are likely to contain unexpected annotations and other types of noises, such as reference links `B0004.1[8]`, missing values `N/A [e]`, inconsistent formatting, etc.

To simplify the parsing process, we have provided an incomplete code snippet below to help you to fill up the `launch_dict`. Please complete the following code snippet with TODOs or you can choose to write your own logic to parse all launch tables:

In [150]:
extracted_row = 0
#Extract each table 
for table_number,table in enumerate(beautiful_soup_obj.find_all('table',"wikitable plainrowheaders collapsible")):
   # get table row 
    for rows in table.find_all("tr"):
        #check to see if first table heading is as number corresponding to launch a number 
        if rows.th:
            if rows.th.string:
                flight_number=rows.th.string.strip()
                flag=flight_number.isdigit()
        else:
            flag=False
        #get table element 
        row=rows.find_all('td')
        #if it is number save cells in a dictonary 
        if flag:
            extracted_row += 1
            launch_dict['Flight No.'].append(flight_number)
            # Flight Number value
            
            datatimelist=date_time(row[0])
            date = datatimelist[0].strip(',')
            launch_dict['Date'].append(date)
            
            # Time value
            time = datatimelist[1]
            launch_dict["Time"].append(time)
              
            # Booster version
            bv=booster_version(row[1])
            if not(bv):
                bv=row[1].a.string
                launch_dict['Version Booster'].append(bv)
            
            # Launch Site
            launch_site = row[2].a.string
            launch_dict['Launch site'].append(launch_site)
            
            # Payload
            payload = row[3].a.string
            launch_dict['Payload'].append(payload)
            
            # Payload Mass
            payload_mass = get_mass(row[4])
            launch_dict['Payload mass'].append(payload_mass)
            
            # Orbit
            orbit = row[5].a.string
            launch_dict['Orbit'].append(orbit)            
            # Customer
            customerTd = row[6]
            if customerTd.a:                
                launch_dict['Customer'].append(customerTd.a.string)
            else:
                launch_dict['Customer'].append(customerTd.string)
            
            # Launch outcome
            # TODO: Append the launch_outcome into launch_dict with key `Launch outcome`
            launch_outcome = list(row[7].strings)[0]
            launch_dict['Launch outcome'].append(launch_outcome)
            
            # Booster landing
            # TODO: Append the launch_outcome into launch_dict with key `Booster landing`
            booster_landing = landing_status(row[8])
            launch_dict['Booster landing'].append(booster_landing.replace('\n', ''))

After you have fill in the parsed launch record values into `launch_dict`, you can create a dataframe from it.

In [152]:
df= pd.DataFrame({ key:pd.Series(value) for key, value in launch_dict.items() })
df.head(50)

,Flight No.,Launch site,Payload,Payload mass,Orbit,Customer,Launch outcome,Version Booster,Booster landing,Date,Time
0,1,CCAFS,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success\n,F9 v1.1,Failure,4 June 2010,18:45
1,2,CCAFS,Dragon,0,LEO,NASA,Success,F9 v1.1,Failure,8 December 2010,15:43
2,3,CCAFS,Dragon,525 kg,LEO,NASA,Success,F9 v1.1,Not attempted,22 May 2012,07:44
3,4,CCAFS,SpaceX CRS-1,"4,700 kg",LEO,NASA,Success\n,F9 v1.1,No attempt,8 October 2012,00:35
4,5,CCAFS,SpaceX CRS-2,"4,877 kg",LEO,NASA,Success\n,F9 v1.1,Not attempted,1 March 2013,15:10
5,6,VAFB,CASSIOPE,500 kg,Polar orbit,MDA,Success,NaN,Uncontrolled,29 September 2013,16:00
6,7,CCAFS,SES-8,"3,170 kg",GTO,SES,Success,NaN,Not attempted,3 December 2013,22:41
7,8,CCAFS,Thaicom 6,"3,325 kg",GTO,Thaicom,Success,NaN,Not attempted,6 January 2014,22:06
8,9,Cape Canaveral,SpaceX CRS-3,"2,296 kg",LEO,NASA,Success\n,NaN,Controlled,18 April 2014,19:25
9,10,Cape Canaveral,Orbcomm-OG2,"1,316 kg",LEO,Orbcomm,Success,NaN,Controlled,14 July 2014,15:15
10,11,Cape Canaveral,AsiaSat 8,"4,535 kg",GTO,AsiaSat,Success,NaN,Not attempted,5 August 2014,08:00
11,12,Cape Canaveral,AsiaSat 6,"4,428 kg",GTO,AsiaSat,Success,NaN,Not attempted,7 September 2014,05:00
12,13,Cape Canaveral,SpaceX CRS-4,"2,216 kg",LEO,NASA,Success,NaN,Uncontrolled,21 September 2014,05:52
13,14,Cape Canaveral,SpaceX CRS-5,"2,395 kg",LEO,NASA,Success,NaN,Failure,10 January 2015,09:47
14,15,Cape Canaveral,DSCOVR,570 kg,HEO,USAF,Success\n,NaN,Controlled,11 February 2015,23:03
15,16,Cape Canaveral,ABS-3A,"4,159 kg",GTO,ABS,Success\n,NaN,Not attempted,2 March 2015,03:50
16,17,Cape Canaveral,SpaceX CRS-6,"1,898 kg",LEO,NASA,Success\n,NaN,Failure,14 April 2015,20:10
17,18,Cape Canaveral,TürkmenÄlem 52°E / MonacoSAT,"4,707 kg",GTO,None,Success\n,NaN,Not attempted,27 April 2015,23:03
18,19,Cape Canaveral,SpaceX CRS-7,"1,952 kg",LEO,NASA,Failure,NaN,Precluded,28 June 2015,14:21
19,20,Cape Canaveral,Orbcomm-OG2,"2,034 kg",LEO,Orbcomm,Success\n,NaN,Success,22 December 2015,01:29
20,21,VAFB,Jason-3,553 kg,LEO,NASA,Success\n,NaN,Failure,17 January 2016,18:42
21,22,Cape Canaveral,SES-9,"5,271 kg",GTO,SES,Success\n,NaN,Failure,4 March 2016,23:35
22,23,Cape Canaveral,SpaceX CRS-8,"3,136 kg",LEO,NASA,Success,NaN,Success,8 April 2016,20:43
23,24,Cape Canaveral,JCSAT-14,"4,696 kg",GTO,SKY Perfect JSAT Group,Success\n,NaN,Success,6 May 2016,05:21
24,25,Cape Canaveral,Thaicom 8,"3,100 kg",GTO,Thaicom,Success\n,NaN,Success,27 May 2016,21:39
25,26,Cape Canaveral,ABS-2A,"3,600 kg",GTO,ABS,Success\n,NaN,Failure,15 June 2016,14:29
26,27,Cape Canaveral,SpaceX CRS-9,"2,257 kg",LEO,NASA,Success\n,NaN,Success,18 July 2016,04:45
27,28,Cape Canaveral,JCSAT-16,"4,600 kg",GTO,SKY Perfect JSAT Group,Success\n,NaN,Success,14 August 2016,05:26
28,29,VAFB,Iridium NEXT,"9,600 kg",Polar,Iridium Communications,Success\n,NaN,Success,14 January 2017,17:54
29,30,KSC,SpaceX CRS-10,"2,490 kg",LEO,NASA,Success\n,NaN,Success,19 February 2017,14:39
30,31,KSC,EchoStar 23,"5,600 kg",GTO,EchoStar,Success\n,NaN,Not attempted,16 March 2017,06:00
31,32,KSC,SES-10,"5,300 kg",GTO,SES,Success,NaN,Success,30 March 2017,22:27
32,33,KSC,NROL-76,C,LEO,NRO,Success\n,NaN,Success,1 May 2017,11:15
33,34,KSC,Inmarsat-5 F4,"6,070 kg",GTO,Inmarsat,Success\n,NaN,Not attempted,15 May 2017,23:21
34,35,KSC,SpaceX CRS-11,"2,708 kg",LEO,NASA,Success\n,NaN,Success,3 June 2017,21:07
35,36,KSC,BulgariaSat-1,"3,669 kg",GTO,Bulsatcom,Success\n,NaN,Success,23 June 2017,19:10
36,37,VAFB,Iridium NEXT,"9,600 kg",LEO,Iridium Communications,Success\n,NaN,Success,25 June 2017,20:25
37,38,KSC,Intelsat 35e,"6,761 kg",GTO,Intelsat,Success\n,NaN,Not attempted,5 July 2017,23:38
38,39,KSC,SpaceX CRS-12,"3,310 kg",LEO,NASA,Success\n,NaN,Success,14 August 2017,16:31
39,40,VAFB,Formosat-5,475 kg,SSO,NSPO,Success\n,NaN,Success,24 August 2017,18:51
40,41,KSC,Boeing X-37B,"4,990 kg",LEO,USAF,Success\n,NaN,Success,7 September 2017,14:00
41,42,VAFB,Iridium NEXT,"9,600 kg",Polar,Iridium Communications,Success\n,NaN,Success,9 October 2017,12:37
42,43,KSC,SES-11,"5,200 kg",GTO,SES S.A.,Success\n,NaN,Success,11 October 2017,22:53:00
43,44,KSC,Koreasat 5A,"3,500 kg",GTO,KT Corporation,Success\n,NaN,Success,30 October 2017,19:34
44,45,Cape Canaveral,SpaceX CRS-13,"2,205 kg",LEO,NASA,Success\n,NaN,Success,15 December 2017,15:36
45,46,VAFB,Iridium NEXT,"9,600 kg",Polar,Iridium Communications,Success,NaN,Controlled,23 December 2017,01:27
46,47,CCAFS,Zuma,C,LEO,Northrop Grumman,Success,NaN,Success,8 January 2018,01:00
47,48,CCAFS,GovSat-1,"4,230 kg",GTO,SES,Success,NaN,Controlled,31 January 2018,21:25
48,49,VAFB,Paz,"2,150 kg",SSO,Hisdesat,Success,NaN,Not attempted,22 February 2018,14:17
49,50,CCAFS,Hispasat 30W-6,"6,092 kg",GTO,Hispasat,Success,NaN,No attempt,6 March 2018,05:33

In [154]:
df.to_csv('spacex_web_scraped.csv', index=False)

We can now export it to a <b>CSV</b> for the next section, but to make the answers consistent and in case you have difficulties finishing this lab. 

Following labs will be using a provided dataset to make each lab independent.

<code>df.to_csv('spacex_web_scraped.csv', index=False)</code>

## Authors

<a href="https://www.linkedin.com/in/yan-luo-96288783/">Yan Luo</a>

<a href="https://www.linkedin.com/in/nayefaboutayoun/">Nayef Abou Tayoun</a>

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By | Change Description      |
| ----------------- | ------- | ---------- | ----------------------- |
| 2021-06-09        | 1.0     | Yan Luo    | Tasks updates           |
| 2020-11-10        | 1.0     | Nayef      | Created the initial version |

Copyright © 2021 IBM Corporation. All rights reserved.